package it.polimi.ingsw.psp12.network.messages;

import it.polimi.ingsw.psp12.model.board.Cell;
import it.polimi.ingsw.psp12.network.enumeration.MsgCommand;

import java.util.ArrayList;

/**
 * Class for a send to the client a list of cell generated by the server
 * @author Mattia Malacarne
 */
public class CellListMsg extends Message
{
    private ArrayList<Cell> cellList;

    /**
     * Init the message with the list of cell created by the server
     * @param listOfCell the list of cell
     */
    public CellListMsg(ArrayList<Cell> listOfCell) {
        super(MsgCommand.CELL_LIST);
        this.cellList = listOfCell;
    }

    public ArrayList<Cell> getCellList()
    {
        return cellList;
    }
}
